name: 'gitdoc-sync-docker'
name: 'gitdoc-sync-docker'
description: 'Build Git repo docs to yuque '
inputs:
  osc_user:
    required: true
  osc_pwd:
    required: true
  yuqueNamespace:
    required: true
  yuqueSite:
    required: true
  yuqueToken:
    required: true    
  gitRepo:
    required: true
  gitBranch:
    required: true
  gitDocToc:
    required: true    
  gitToken:
    require: true
  gitUser:
    require: true
runs:
  using: 'composite'
  steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v2
    - name: Login to Aliyun Container Registry
      run: docker login --username ${{ inputs.osc_user }} --password ${{ inputs.osc_pwd }} oscollege-registry.cn-hangzhou.cr.aliyuncs.com
      shell: bash

    - name: Start Docker container
      run: |
        docker run -d -p 8080:8777 -e ns='${{ inputs.yuqueNamespace }}' -e user='${{inputs.gitUser}}' -e site='${{ inputs.yuqueSite }}' -e token='${{ inputs.yuqueToken }}' -e repo='${{inputs.gitRepo}}' -e toc='${{inputs.gitDocToc}}' -e gittoken='${{inputs.gitToken}}'  --name git-to-yuque -t oscollege-registry.cn-hangzhou.cr.aliyuncs.com/oscollege/git-to-yuque:latest
      shell: bash

    - name: Wait for container to start
      run: docker logs git-to-yuque
      shell: bash
