name: 'gitdoc-sync-docker'
description: 'Build Git repo docs to yuque '
inputs:
  osc_user:
    required: true
  osc_pwd:
    required: true
  yuqueNamespace:
    required: true
  yuqueSite:
    required: true
  yuqueToken:
    required: true    
  gitRepo:
    required: true
  gitBranch:
    required: true
  gitDocToc:
    required: true    

runs:
    using: 'node16'
    main: 'dist/index.js'
